### ISSUE TITLE
Rewrite the README

### ISSUE THREAD

**Issue by krzhu** [magical-eda/MAGICAL#10]
Rewrite the README.md. Highlight the following things.
- Now we are closer to 1.0 release. Whats' new?
- The software structure. C++ individual components and Python Magical flow.
- How to build and install the components? How to use the Magical tool as a whole.
- Instructions on running example benchmark circuits.

**Comment by krzhu** [comment]
https://github.com/magical-eda/MAGICAL/pull/20 is attached to this.

**Comment by baloneymath** [comment]
Should update and fix the example
