### ISSUE TITLE
An error occurred while running the OTA2 example,capacitor and resistor devices in netlist are not operational

### ISSUE THREAD

**Issue by lhjey** [magical-eda/MAGICAL#42]
![image](https://user-images.githubusercontent.com/49546927/107044800-bff8b100-67ff-11eb-8e51-abb3d8c47b0e.png)
Is it because the device attribute unit is not recognized?
At the same time, I would like to ask how to run the exported high-hierarchy netlist. Is it need to modify the netlist format?
Thanks!

**Comment by jayl940712** [comment]
Hi, can you try to reinstall gdspy package in version 1.4.1?

**Comment by lhjey** [comment]
I am trying to install version 1.4.1, but I encountered some errors about gdspy.

Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement gdspy==1.4.1
ERROR: No matching distribution found for gdspy==1.4.1
My original version is 1.4.

**Comment by lhjey** [comment]
![image](https://user-images.githubusercontent.com/49546927/107118817-352abb80-68be-11eb-8118-a07f186a6e62.png)
![image](https://user-images.githubusercontent.com/49546927/107118829-4d023f80-68be-11eb-8c2c-785f49172124.png)
![image](https://user-images.githubusercontent.com/49546927/107118876-b8e4a800-68be-11eb-9804-41c500246db5.png)

Hi, I have installed version 1.4.1, but because of the gdspy release, version 1.4 is still displayed. But it is actually version 1.4.1. After that, I tried to run the ota2 example, but the same error occurred as before.

**Comment by jayl940712** [comment]
Hi are you sure its [](https://github.com/heitzmann/gdspy/releases/tag/v1.4.1)?
I dont seem to get a matched line 6066 for __init__.py. I think that error matches with 
[](https://github.com/heitzmann/gdspy/releases/tag/v1.4).
If pip install has some issues can you try to compile v1.4.1 with the source code?

**Comment by jayl940712** [comment]
Can you try to compile my version of gdspy? [https://github.com/jayl940712/gdspy/tree/constraint-graph](https://github.com/jayl940712/gdspy/tree/constraint-graph)
Try run the following:
```
    git clone https://github.com/jayl940712/gdspy
    pip install gdspy/
```

**Comment by lhjey** [comment]
Hi, I reinstalled gdspy according to your suggestion, and it has been running correctly.
Thank you for your help！

**Comment by jayl940712** [comment]
Great. I will close this issue.
