### ISSUE TITLE
issue in building 

### ISSUE THREAD

**Issue by AmrMohamedRashed** [magical-eda/MAGICAL#46]
I have tried to run the following command but it gives me an error, can you help?
Command: ./build
Error:  https://drive.google.com/file/d/17JOBQbn23Y62BHpwyoU4zWvw3XFfjwBK/view?usp=sharing

gcc and g++ version 8.2 are installed and I am using Debian.

**Comment by krzhu** [comment]
Hello.

We have now have a Docker container available for MAGICAL. I just merged the Docker branch into master. You can follow "Build with Docker" in readme. For installing on your own machine, you can refer to [Dockerfile ](https://github.com/magical-eda/MAGICAL/blob/master/Dockerfile) for the steps.
