### ISSUE TITLE
device_generation not found

### ISSUE THREAD

**Issue by melnimr** [magical-eda/MAGICAL#55]
I can not find where the package device_generation is being defined. I see these imports commands:

from device_generation import *

but there is no files that exist corresponding to that package.

**Comment by krzhu** [comment]
You need to install the device_generation submodule first.  See: https://github.com/magical-eda/MAGICAL/blob/199ab0719f85f74c79bf85a556118b132988a5fe/build.sh

Or you can use the Docker image (see README).
