### ISSUE TITLE
Adds the benchmark circuits

### ISSUE THREAD

**Issue by krzhu** [magical-eda/MAGICAL#9]
Add the benchmark circuits to the repo. Remove the PDK-related parameters.

**Comment by krzhu** [comment]
We need to finish this before heading into https://github.com/magical-eda/MAGICAL/issues/18 https://github.com/magical-eda/MAGICAL/issues/17

**Comment by jayl940712** [comment]
Copied over non-hierarchial examples from VERSION-0.5. #21 
Need to add hierarchical example for ADC1 and ADC2.
What are we going to do about tech file inputs.

**Comment by krzhu** [comment]
> Copied over non-hierarchial examples from VERSION-0.5. #21
> Need to add hierarchical example for ADC1 and ADC2.
> What are we going to do about tech file inputs.

What tech files are needed? LEF? We should have some fake PDK.

**Comment by jayl940712** [comment]
I think only the lef is needed for P&R now. The device_generation already includes a dummy glovar.py parameter list.

**Comment by krzhu** [comment]
> I think only the lef is needed for P&R now. The device_generation already includes a dummy glovar.py parameter list.

Let me see whether ISPD contest ones work.

**Comment by krzhu** [comment]
> > I think only the lef is needed for P&R now. The device_generation already includes a dummy glovar.py parameter list.
> 
> Let me see whether ISPD contest ones work.

@baloneymath We also need an alternative for Cadence Virtuoso techfile.
